

# Site Settings
title: 						"Jeff Knox Blog"
email: 						"knoxjeffrey@outlook.com"
phone:                      "+447775682459"
description: 				"Web development projects, thoughts, knowledge and ideas"
baseurl: 					""
url: 						"https://knoxjeffrey.github.io"
logourl: 					"/assets/img/bloglogo.jpg"
fa-logo: 					"fa-bookmark-o"
paginate: 					5


# Author Settings
author_name: 				"Jeff Knox"
author_url: 				"https://github.com/knoxjeffrey"
author_bio: 				"Ruby on Rails developer based in Edinburgh, UK."
author_image: 				"/assets/img/authorimage.jpg"


# Social Settings
twitter_url: 				"https://twitter.com/jeff_r_knox"
facebook_url: 				"https://www.facebook.com/knoxjeffrey"
github_url:  				"https://github.com/knoxjeffrey"
youtube_url:  				""
dribbble_url:  				""
googleplus_url: 			""
instagram_url:  			""
pinterest_url:  			""
linkedin_url:  				"https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile"


# Theme Settings
theme_disqus_shortname: 	"knoxjeffrey"
theme_google_comments: 		false
theme_analytics_id: 		"UA-58139054-1"
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

kramdown:
  input: GFM
  syntax_highlighter: rouge
